---
kube_oidc_auth: true
kube_oidc_url: "https://keycloak.{{ domain }}/auth/realms/{{ keycloak_realm }}"
kube_oidc_client_id: "kubernetes"
kube_oidc_username_claim: "email"
kube_oidc_groups_claim: "groups"
kube_oidc_ca_file: "/etc/kubernetes/pki/freeipa-ca.crt"
