---
# Default variables for identity-certmanager role
ca_cert_src: "/opt/vmstation-org/cluster-setup/scripts/certs/ca.cert.pem"
ca_key_src: "/opt/vmstation-org/cluster-setup/scripts/certs/ca.key.pem"
secret_name: freeipa-ca
clusterissuer_name: freeipa-ca-issuer
template_dest: "/tmp/clusterissuer-freeipa.yml"
backup_dir: /root/identity-backup
